### ISSUE TITLE
Locally setting up

### ISSUE THREAD

**Issue by Remus-Catrina** [matthewdowns/helium-payment-calculator#79]
Hello,

I've tried to set up the payment calculator on a Rocky Linux machine without success. 

NPM keeps hitting me with this error, maybe you can help.

```
[webpack-cli] /home/Remus/helium-payment-calculator/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Server.getServerTransport (/home/Remus/helium-payment-calculator/node_modules/webpack-dev-server/lib/Server.js:1191:28)
    at Server.createWebSocketServer (/home/Remus/helium-payment-calculator/node_modules/webpack-dev-server/lib/Server.js:1757:38)
    at Server.start (/home/Remus/helium-payment-calculator/node_modules/webpack-dev-server/lib/Server.js:2305:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! helium-payment-calculator@1.0.0 start: `webpack serve --open --mode development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the helium-payment-calculator@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-11T04_19_22_646Z-debug.log

```
You can also check the logs below.

```
[root@localhost helium-payment-calculator]# cat /root/.npm/_logs/2021-12-11T04_19_22_646Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'start' ]
2 info using npm@6.14.11
3 info using node@v10.24.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle helium-payment-calculator@1.0.0~prestart: helium-payment-calculator@1.0.0
6 info lifecycle helium-payment-calculator@1.0.0~start: helium-payment-calculator@1.0.0
7 verbose lifecycle helium-payment-calculator@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle helium-payment-calculator@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/Remus/helium-payment-calculator/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin
9 verbose lifecycle helium-payment-calculator@1.0.0~start: CWD: /home/Remus/helium-payment-calculator
10 silly lifecycle helium-payment-calculator@1.0.0~start: Args: [ '-c', 'webpack serve --open --mode development' ]
11 silly lifecycle helium-payment-calculator@1.0.0~start: Returned: code: 2  signal: null
12 info lifecycle helium-payment-calculator@1.0.0~start: Failed to exec start script
13 verbose stack Error: helium-payment-calculator@1.0.0 start: `webpack serve --open --mode development`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid helium-payment-calculator@1.0.0
15 verbose cwd /home/Remus/helium-payment-calculator
16 verbose Linux 4.18.0-348.2.1.el8_5.x86_64
17 verbose argv "/usr/bin/node" "/bin/npm" "start"
18 verbose node v10.24.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 2
22 error helium-payment-calculator@1.0.0 start: `webpack serve --open --mode development`
22 error Exit status 2
23 error Failed at the helium-payment-calculator@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
```

I've looked into different github threads and it looks like to be a node version issue but at the latest stable version.

```
[root@localhost helium-payment-calculator]# node --version
v10.24.0
[root@localhost helium-payment-calculator]# npm --version
6.14.11

```

Not sure what I'm missing here, hope you can assist. 

Regards,
Remus

**Comment by matthewdowns** [comment]
> Hello,
> 
> I've tried to set up the payment calculator on a Rocky Linux machine without success.
> 
> NPM keeps hitting me with this error, maybe you can help.
> 
> ```
> [webpack-cli] /home/Remus/helium-payment-calculator/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:10
>   static heartbeatInterval = 1000;
>                            ^
> 
> SyntaxError: Unexpected token =
>     at Module._compile (internal/modules/cjs/loader.js:723:23)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Server.getServerTransport (/home/Remus/helium-payment-calculator/node_modules/webpack-dev-server/lib/Server.js:1191:28)
>     at Server.createWebSocketServer (/home/Remus/helium-payment-calculator/node_modules/webpack-dev-server/lib/Server.js:1757:38)
>     at Server.start (/home/Remus/helium-payment-calculator/node_modules/webpack-dev-server/lib/Server.js:2305:12)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! helium-payment-calculator@1.0.0 start: `webpack serve --open --mode development`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the helium-payment-calculator@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-12-11T04_19_22_646Z-debug.log
> ```
> 
> You can also check the logs below.
> 
> ```
> [root@localhost helium-payment-calculator]# cat /root/.npm/_logs/2021-12-11T04_19_22_646Z-debug.log
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/bin/npm', 'start' ]
> 2 info using npm@6.14.11
> 3 info using node@v10.24.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle helium-payment-calculator@1.0.0~prestart: helium-payment-calculator@1.0.0
> 6 info lifecycle helium-payment-calculator@1.0.0~start: helium-payment-calculator@1.0.0
> 7 verbose lifecycle helium-payment-calculator@1.0.0~start: unsafe-perm in lifecycle true
> 8 verbose lifecycle helium-payment-calculator@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/Remus/helium-payment-calculator/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin
> 9 verbose lifecycle helium-payment-calculator@1.0.0~start: CWD: /home/Remus/helium-payment-calculator
> 10 silly lifecycle helium-payment-calculator@1.0.0~start: Args: [ '-c', 'webpack serve --open --mode development' ]
> 11 silly lifecycle helium-payment-calculator@1.0.0~start: Returned: code: 2  signal: null
> 12 info lifecycle helium-payment-calculator@1.0.0~start: Failed to exec start script
> 13 verbose stack Error: helium-payment-calculator@1.0.0 start: `webpack serve --open --mode development`
> 13 verbose stack Exit status 2
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:198:13)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:198:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:982:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 14 verbose pkgid helium-payment-calculator@1.0.0
> 15 verbose cwd /home/Remus/helium-payment-calculator
> 16 verbose Linux 4.18.0-348.2.1.el8_5.x86_64
> 17 verbose argv "/usr/bin/node" "/bin/npm" "start"
> 18 verbose node v10.24.0
> 19 verbose npm  v6.14.11
> 20 error code ELIFECYCLE
> 21 error errno 2
> 22 error helium-payment-calculator@1.0.0 start: `webpack serve --open --mode development`
> 22 error Exit status 2
> 23 error Failed at the helium-payment-calculator@1.0.0 start script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> ```
> 
> I've looked into different github threads and it looks like to be a node version issue but at the latest stable version.
> 
> ```
> [root@localhost helium-payment-calculator]# node --version
> v10.24.0
> [root@localhost helium-payment-calculator]# npm --version
> 6.14.11
> ```
> 
> Not sure what I'm missing here, hope you can assist.
> 
> Regards, Remus

Hi @Remus-Catrina, can you try installing Node version 12 or higher?
